---
- name: create php dirs
  file:
    path: "{{ item|safe|trim }}"
    state: directory
    owner: "{{ php_user }}"
    group: "{{ php_group }}"
    mode: 0777
    recurse: yes
  changed_when: "False"
  with_items:
    - "{{ php_opt_dir }}"
    - "{{ php_log_dir }}"
    - "{{ php_config_dir }}"
    - "{{ php_config_dir }}/pool"
  tags:
    - php