---
- name: setup group
  group:
    name="{{ php_group }}"
    system=yes
  tags:
    - php

- name: setup user
  user:
    name="{{ php_user }}"
    system=yes
    group="{{ php_group }}"
  tags:
    - php
